---
modbus:
  host: <%= ENV['MB_HOST'] %>
  port: 502
  req: 60
mysql:
  host: <%= ENV['MYSQL_HOST'] %>
  user: <%= ENV['MYSQL_USER'] %>
  pass: <%= ENV['MYSQL_PASS'] %>
  dbase: <%= ENV['MYSQL_DBASE'] %>
  table: SolarMetrics
